version: 0.0.{build}
services: iis
install:
- ps: >-
    (new-object net.webclient).DownloadFile('https://www.mathworks.com/supportfiles/downloads/R2016b/deployment_files/R2016b/installers/win64/MCR_R2016b_win64_installer.exe', 'mcr_setup.exe')

    mcr_setup.exe -mode silent -agreeToLicense yes
before_build:
- cmd: >-
    cd src

    nuget restore
build:
  project: ./src/Spectre.sln
  parallel: true
  verbosity: normal