version: 1.22.7.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
environment:
  nuget_user:
    secure: kWtlS49bKmP0IFXmdvDHmxGI8mS0xQGrwiJoco9nYtA=
  nuget_password:
    secure: Pzvx2CQjxp8eCBP+nFI2eg==
  appveyor_rdp_password:
    secure: Pzvx2CQjxp8eCBP+nFI2eg==
configuration:
  - Debug
  - Release
services: iis

# skip branch build if there is an active pull request
skip_branch_with_pr: true

init:
- cmd: echo Project - %APPVEYOR_PROJECT_NAME%
- cmd: echo Worker image - %APPVEYOR_BUILD_WORKER_IMAGE%
- cmd: echo Branch - %APPVEYOR_REPO_BRANCH%
- cmd: echo Author - %APPVEYOR_REPO_COMMIT_AUTHOR%
- cmd: echo Commit - %APPVEYOR_REPO_COMMIT%
#- cmd: echo (%APPVEYOR_REPO_COMMIT_MESSAGE%)
#- cmd: echo (%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%)
- cmd: echo Platform - %PLATFORM%
- cmd: echo Configuration - %CONFIGURATION%
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

nuget:
  account_feed: false
  project_feed: false

install:
- cmd: C:\projects\spectre\scripts\restore_nugets.bat

build_script:
- cmd: msbuild "C:\projects\spectre\src\Spectre.sln" /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /m /verbosity:quiet /p:DeployOnBuild=true /p:PublishProfile=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
- ps: C:\projects\spectre\scripts\BindPageToIisAndCreateDataDir.ps1 -AppVeyor

test_script:
- cmd: C:\projects\spectre\scripts\test_native_code.bat

on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmd: C:\projects\spectre\scripts\upload-frontend-test-results.bat
