version: 0.0.{build}
services: iis
install:
- ps: >-
    prep\install_mcr.ps1
before_build:
- cmd: >-
    cd src

    nuget restore
build:
  project: ./src/Spectre.sln
  parallel: true
  verbosity: normal