version: 0.0.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
configuration:
  - Debug
  - Release
services: iis
install:
- ps: >-
    scripts\enable_assembly_log.ps1
    
    scripts\install_mcr.ps1
before_build:
- cmd: >-
    cd src

    nuget restore
    
    cd ..
build:
  project: ./src/Spectre.sln
  parallel: true
  verbosity: normal
test_script:
- cmd: >-
    scripts\run_not_excluded_tests.bat Spectre.Algorithms.Tests