version: 0.3.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.3.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
configuration:
  - Debug
  - Release
services: iis

install:
- ps: C:\projects\spectre\scripts\InstallNode.ps1

before_build:
- cmd: C:\projects\spectre\scripts\restore_nugets.bat
build_script:
- cmd: msbuild "C:\projects\spectre\src\Spectre.sln" /m /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: C:\projects\spectre\scripts\build_ng2_client.bat

test_script:
- cmd: C:\projects\spectre\scripts\test_dotnet.bat --except Algorithm
- cmd: C:\projects\spectre\scripts\test_frontend.bat
- cmd: C:\projects\spectre\scripts\test_frontend_e2e.bat
