version: 0.1.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
configuration:
  - Debug
  - Release
services: iis

install:
- ps: .\scripts\InstallNode.ps1

before_build:
- cmd: .\scripts\restore_nugets.bat
build_script:
- cmd: msbuild "C:\projects\spectre\src\Spectre.sln" /m /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: .\scripts\build_ng2_client.bat
# build:
#   project: ./src/Spectre.sln
#   parallel: true
#   verbosity: quiet
after_build:
# - cmd: .\scripts\build_ng2_client.bat
- ps: C:\projects\spectre\scripts\BindPageToIIS.ps1

test:
  categories:
    except:
      - Algorithm
test_script:
- cmd: .\scripts\test_frontend_e2e.bat
