version: 0.0.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
configuration:
  - Debug
#  - Release
services: iis
install:
- ps: >-
    prep\install_mcr.ps1
before_build:
- cmd: >-
    cd src

    nuget restore
build:
  project: ./src/Spectre.sln
  parallel: true
  verbosity: normal