version: 1.0.0.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
configuration:
  - Debug
#  - Release
services: iis

install:
#- ps: C:\projects\spectre\scripts\InstallNode.ps1

before_build:
- cmd: C:\projects\spectre\scripts\restore_nugets.bat
build_script:
- cmd: msbuild "C:\projects\spectre\src\Spectre.sln" /m /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#- cmd: C:\projects\spectre\scripts\build_ng2_client.bat
after_build:
#- ps: C:\projects\spectre\scripts\BindPageToIisAndCreateDataDir.ps1 -AppVeyor
#- cmd: C:\projects\spectre\scripts\package_project.bat "DiviK.zip" Spectre.DivikWpfClient

test_script:
#- cmd: C:\projects\spectre\scripts\test_dotnet.bat --except Algorithm
#- cmd: C:\projects\spectre\scripts\test_frontend.bat
#- cmd: C:\projects\spectre\scripts\test_frontend_e2e.bat

#artifacts:
#- path: DiviK.zip
#  name: DivikExecutables

#deploy:
#- provider: GitHub
#  release: Spectre-v$(appveyor_build_version)
#  auth_token:
#    secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
#  artifact: DivikExecutables
#  draft: true
#  on:
#    CONFIGURATION: Release

notifications:
- provider: Webhook
  url: https://hooks.glip.com/webhook/529ac2aa-010d-4f5f-bf15-d49ea8091196
#    secure: V16hjhyXfcLNyhNUih9v1GBs2+lmplDr/5q28bfO5JtvCquVQYTtCpkFUicVp7cOd5FX4nrByFu0jSeU8bfVHUmup/CilGIjzv+kxltPTVA=
  method: POST
  content_type: application/json
  body: >-
    {
      "icon": "https://www.appveyor.com/assets/img/appveyor-logo-256.png",
      "activity": "AppVeyor",
      "title": "Build {{buildVersion}} {{#failed}}failed{{/failed}}{{#passed}}passed{{/passed}}",
      "body": "{{#isPullRequest}}Pull request: {{pullRequestId}}{{/isPullRequest}}
      Branch: {{branch}}
      Commit: {{commitId}} {{commitMessage}}
      Author: {{commitAuthor}}
      [Details]({{buildUrl}})"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true