version: 0.0.{build}
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
configuration:
  - Debug
  - Release
services: iis
before_build:
- cmd: .\scripts\restore_nugets.bat
build:
  project: ./src/Spectre.sln
  parallel: true
  verbosity: quiet
test:
  categories:
    except:
      - Algorithm
cache:
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages -> **\packages.config
# project.json cache
  - '%USERPROFILE%\.nuget\packages -> **\project.json'
  - dependencies.zip
