apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: spectre
    role: frontend
spec:
  type: NodePort
  selector:
    component: spectre
    role: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
